### ISSUE TITLE
Ajuda

### ISSUE THREAD

**Issue by mfgjunqueira** [thevtm/CartolaFCScraper#1]
Estou tentando rodar o Scraper localmente, mas encontro o erro abaixo. Pode me ajudar? Valeu!

![scraper_error](https://cloud.githubusercontent.com/assets/11592915/7675283/faf3c812-fd0c-11e4-93ca-a039b38e1a26.PNG)

**Comment by thevtm** [comment]
Você precisa colocar seu login/senha nas variaveis.

```python
LOGIN_EMAIL = "LoginCartolaFC"
LOGIN_SENHA = "SenhaCartolaFC"
```

**Comment by mfgjunqueira** [comment]
Valeu!
