### ISSUE TITLE
Valores iguais

### ISSUE THREAD

**Issue by mfgjunqueira** [thevtm/CartolaFCScraper#2]
Opa, beleza?
Reparei que há 2 casos de valores iguais para um mesmo clube nas colunas "Clube", "PartidaCasa" e "PartidaVisitante":

* "cor" para "Corinthians" e "Coritiba" (geralmente "COR" e "CTB")
* "atl" para "Atlético-MG" e "Atlético-PR" (geralmente "AMG" e "CAP")

Só é possível diferenciá-los no formato atual cruzando com a informação da coluna "Mando" (mandante no próximo jogo) e substituindo o valor. Mas olhando o JSON acho que é possível corrigir puxando outros valores:

* de "clube", "partida_clube_casa" e "partida_clube_visitante"
* puxar "nome" ou "slug" ao invés de "abreviacao"

Espero que ajude... abraço!

**Comment by thevtm** [comment]
Arrumado no be74a60ad004ad7e4ce540509607e6ab01eb7cf9, utilizando 'slug' ao inves de 'abreviacao'.

Obrigado pela ajuda!
